spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/hr_dental?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hryj6666
    initialSize: 1
    minIdle: 1
    maxActive: 20
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#mybatis配置
mybatis:
  type-aliases-package: com.yidusoft.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888

logging:
   level:
     com:
       yidusoft: DEBUG
wx:
  mp:
    configs:
      - appId: wx015e8773b2c769fe  #（一个公众号的appid）
        secret: a97a05a7fdd2bc9d7e795d3bc8c7869a #（公众号的appsecret）
        token: linkbly #（接口配置里的Token值）
        aesKey: 111 #（接口配置里的EncodingAESKey值）
#        appId: 2222 #（另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111