spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/hr_dental?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
  jpa:
    hibernate:
      ddl-auto: update
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#  mvc:
#    favicon:
#      enabled: false
  redis:
      host: localhost
      port: 6379
      timeout: 0
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
server:
  port: 8080

logging:
   level:
     com:
       yidusoft:
           project: debug